// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJ85le2rfFE7zQAdj8PpHY34qGSLKefA',
    appId: '1:724999131137:web:9fc919322d65746235f000',
    messagingSenderId: '724999131137',
    projectId: 'crescereanalytics',
    authDomain: 'crescereanalytics.firebaseapp.com',
    storageBucket: 'crescereanalytics.appspot.com',
    measurementId: 'G-95XZEP5BHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa5xATTpsP_W3dqFGwu3wLcRPoOi-k7is',
    appId: '1:724999131137:android:a8ad9e42979e652135f000',
    messagingSenderId: '724999131137',
    projectId: 'crescereanalytics',
    storageBucket: 'crescereanalytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxPDdAxuZjqeinie25JgGhrjXGTaffbs',
    appId: '1:724999131137:ios:79465e79456d0db535f000',
    messagingSenderId: '724999131137',
    projectId: 'crescereanalytics',
    storageBucket: 'crescereanalytics.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHxPDdAxuZjqeinie25JgGhrjXGTaffbs',
    appId: '1:724999131137:ios:3fafeabc134fcb7635f000',
    messagingSenderId: '724999131137',
    projectId: 'crescereanalytics',
    storageBucket: 'crescereanalytics.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
