name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CRESCEREANALYTICS }}
          channelId: live
          projectId: crescereanalytics
          expires: 7d
          entryPoint: .
          firebaseToolsVersion: latest
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.19.3-x64
          PUB_CACHE: /home/runner/.pub-cache
